# version: '3.8'
name: "sipenjamu-v2"
services:
  webserver:
    image: nginx:alpine
    container_name: sipenjamu.webserver
    restart: unless-stopped
    tty: true
    depends_on:
      - backend
      - frontend
    ports:
      - "2001:80"
    volumes:
      - ./:/var/www/
      - ./etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - sipenjamu.network

  backend:
    build:
      context: .
      dockerfile: ./etc/php/Dockerfile
    image: sipenjamu.be/php:8.3.11
    container_name: sipenjamu.be
    restart: unless-stopped
    tty: true
    environment:
      TZ: Asia/Jakarta
    volumes:
      - ./:/var/www/
      # - ./be/storage/logs/:/var/www/be/storage/logs/
      - ./etc/php/conf.d/docker.ini:/usr/local/etc/php/conf.d/docker.ini
      - ./etc/php/supervisor/:/etc/supervisor/
    networks:
      - mysql-network
      - sipenjamu.network

  frontend:
    build:
      context: .
      dockerfile: ./etc/node/Dockerfile
    image: sipenjamu.fe/node:21.6
    container_name: sipenjamu.fe
    restart: unless-stopped
    tty: true
    depends_on:
      - backend
    environment:
      TZ: Asia/Jakarta
    # volumes:
    #   - ./fe:/app
    #   - ./fe/node_modules:/app/node_modules
    working_dir: /app
    networks:
      - sipenjamu.network

#Networks
networks:
  sipenjamu.network:
    driver: bridge
    name: sipenjamu.network
  mysql-network:
    driver: bridge
    name: mysql-network
    external: true
