# version: '3.8'
name: "oncology-v2"
services:
  webserver:
    image: nginx:alpine
    container_name: oncology.webserver
    restart: unless-stopped
    tty: true
    depends_on:
      - backend
      - frontend
    ports:
      - "1012:80"
    volumes:
      - ./:/var/www/
      - ./etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - oncology.network

  backend:
    build:
      context: .
      dockerfile: ./etc/php/Dockerfile
    image: oncology.be/php:8.3.11
    container_name: oncology.be
    restart: unless-stopped
    tty: true
    environment:
      TZ: Asia/Jakarta
    volumes:
      - ./:/var/www/
      # - ./be/storage/logs/:/var/www/be/storage/logs/
      - ./etc/php/conf.d/docker.ini:/usr/local/etc/php/conf.d/docker.ini
      - ./etc/php/supervisor/:/etc/supervisor/
    networks:
      - mysql-network
      - oncology.network

  frontend:
    build:
      context: .
      dockerfile: ./etc/node/Dockerfile
    image: oncology.fe/node:21.6
    container_name: oncology.fe
    restart: unless-stopped
    tty: true
    depends_on:
      - backend
    environment:
      TZ: Asia/Jakarta
    volumes:
      - ./fe:/app
      - /app/node_modules
    working_dir: /app
    networks:
      - oncology.network
      # - webserver-network

#Networks
networks:
  oncology.network:
    driver: bridge
    name: oncology.network
  mysql-network:
    driver: bridge
    name: mysql-network
    external: true
  # webserver-network:
  #   driver: bridge
  #   name: webserver-network
  #   external: true

x-casaos:
  author: self
  category: self
  hostname: ""
  index: /
  is_uncontrolled: true
  port_map: "1012"
  scheme: http
  title:
    custom: Oncology
